language: python
python:
    - "2.7"
script: nosetests
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get update -qq
install:
    - sudo apt-get install python-pyside
    - sudo apt-get install pyside-tools
    - pip install pyparsing epydoc sphinx nose  --use-mirrors
    - make build
notifications:
    email: 
        recipients:
            - islam.ali.mail@gmail.com
        on_success: change
        on_failure: always
